### ISSUE TITLE
BME280 is not accessible with ESP32-MCU

### ISSUE THREAD

**Issue by imalipusram** [bolderflight/bme280#2]
Hi, 

I'm trying to access a BME 280 with an NodeMCU ESP32-S using the BME280 library.

I2C scanner finds the device, but BME280 is reporting that it can't communicate with the sensor.
Tried with the module set to both addresses (0x76 and 0x77, and also with the BME280 alone on the bus). I get the same error message when running the Basic_I2C example. The other sensor on the bus (a VL53L0X laser distance chip) is responding.

Tested the whole scenario with two BME280 modules, with the identical results.

bme.begin() is returning a -1.

Output from a small sketch returning the values for SCL and SDA, scanning the bus and the trying to initialize the BME280:
```
I2C port:
SCL: 22
SDA: 21

Scanning I2C Bus for clients:
Scanning...
I2C device found at address 0x29  !
I2C device found at address 0x77  !
done

bme_status: -1
Error communicating with sensor, check wiring and I2C address
```
Is your library specific for the Teensy so it won't work with other units, like e.g. the ESP32?

Thanks for your help!
Wolfgang

**Comment by flybrianfly** [comment]
No, it was written to use the generic TwoWire interface to be as generic with any Arduino as possible. I suspect that the [ESP32 Core](https://github.com/espressif/arduino-esp32/blob/master/libraries/Wire/src/Wire.h) is doing something unexpected. Can you post your code for your I2C scanner? I'd like to see an example of how I2C is on the ESP32.

**Comment by imalipusram** [comment]
Yep, here you are. Code excerpt:
 ```
void i2cscan() // scans I2C bus for clients
  // code is running around on the net, without an attributable "original source" 

{
  Wire.begin(SDA,SCL,100000);

  Serial.println (F("I2C port:")); 
  Serial.print (F("SCL: "));
  Serial.println(String(SCL));
  Serial.print (F("SDA: "));
  Serial.println(String(SDA));
  Serial.println();



  Serial.println F(("Scanning I2C Bus for clients:"));

  byte error, address;
  int nDevices =0;

  for(address = 1; address < 127; address++ ) 
  {
    // The i2c_scanner uses the return value of
    // the Write.endTransmisstion to see if
    // a device did acknowledge to the address.
    Wire.beginTransmission(address);
    error = Wire.endTransmission();

    if (error == 0)
    {
      Serial.print("I2C device found at address 0x");
      if (address<16) Serial.print(F("0")); // adds a leading zero if one digit number
      Serial.print(address,HEX);
      Serial.println(F("."));

      nDevices++;
    }
    else if (error==4) 
    {
      Serial.print(F("Unspecified error at address 0x"));
      if (address<16) Serial.print(F("0"));
      Serial.println(address,HEX);
    }    

 
  } // end of for loop counting up addresses
  
    Serial.print(F("I2C scan done. "));
    Serial.print(String(nDevices));
    Serial.println(F(" devices found.\r\n"));
  
}  
```
The complete .ino file is here:
[I2C_test_2.ino.zip](https://github.com/bolderflight/BME280/files/2485961/I2C_test_2.ino.zip)

If you search the net for "i2c scanner", you'll get many hits. I don't remember which code I initially started with, and the author of that code writes in his source that he can't trace it back. sorry. But it's rather straightforward anyway. 

ESP32 has its own Wire.h, according to the compiler output.

I haven't found where SDA and SCL actually have been defined. Possibly the are key to the solution.

Best regards
Wolfgang

**Comment by flybrianfly** [comment]
Thanks, can you try the library attached and see if it works for you?

Brian
[BME280.zip](https://github.com/bolderflight/BME280/files/2488007/BME280.zip)

**Comment by imalipusram** [comment]
Hi Brian,

Thanks for the files. Tested them:

Renamed the library and the includes to BME280_test.*, installed it as zip library from within the Arduino IDE and adjusted the #includes in the code appropriately.

Loaded and compiled the Basic_I2C example.

Errors:

/home/wo/Arduino/libraries/BME280_test/src/BME280_test.cpp: In member function 'int BME280::readSensor()':
/home/wo/Arduino/libraries/BME280_test/src/BME280_test.cpp:218:1: error: control reaches end of non-void function [-Werror=return-type]

Added "return -9999;" at line 218

-> compiles

Executing:

Still the same error message: "Error communicating with sensor, check wiring and I2C address "

In my own code the sensor is found, bme.begin(); returns -1 as before.

Best regards

Wolfgang

**Comment by flybrianfly** [comment]
That's annoying that the compiler is treating this as an error - used to just be a warning. Can you try Basic_I2C with the attached library?
[BME280.zip](https://github.com/bolderflight/BME280/files/2489557/BME280.zip)

**Comment by imalipusram** [comment]
Still the same result. Just no compiler warning / error.
Would it be helpful if I attached the whole compiling protocol that you can see all code/libraries that is used for the ESP?

**Comment by flybrianfly** [comment]
Might be related to these issues:
https://github.com/bolderflight/MPU9250/issues/38
https://github.com/espressif/arduino-esp32/issues/1998
